name: run-tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.2, 8.3, 8.4]
        laravel: ['9.*', '10.*', '11.*', '12.*']
        dependency-version: [prefer-stable]
        testbench: ['7.*', '8.*', '9.*', '10.*']
        include:
          - laravel: 9.*
            testbench: 7.*
            php: 8.1
          - laravel: 10.*
            testbench: 8.*
            php: 8.2
          - laravel: 11.*
            testbench: 9.*
            php: '8.2'
          - laravel: 12.*
            testbench: 10.*
            php: '8.4'
        exclude:
          - laravel: 9.*
            testbench: 8.*
          - laravel: 10.*
            testbench: 7.*
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - T${{ matrix.testbench }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE_KEY }}"
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Execute tests
        run: vendor/bin/phpunit
